### ISSUE TITLE
Accepts only pickles?  (Not ASTs?)

### ISSUE THREAD

**Issue by Zearin** [cucumber/microcuke#3]
Does microcuke only accept Gherkin3 pickles?  Does it not accept the JSON AST output?

**Comment by aslakhellesoy** [comment]
The AST must be conpiled to pickles first. The compiler must be implemented in Gherkin3 - see ruby/js/java impls.

If you're working on python, start by writing the compiler.

**Comment by Zearin** [comment]
> The AST must be conpiled to pickles first. The compiler must be implemented in Gherkin3 - see ruby/js/java impls.
> 
> If you're working on python, start by writing the compiler.

Oooh, okay!  This is a new type of project for me, but I’m excited to get started.  (Already started translating some JS to Python!)

**Quick Q:** Does the compiler take in a JSON AST and output a pickle?

**Comment by aslakhellesoy** [comment]
One feature AST in, list of pickles out. Gherkin3 has cross platform tests for this

**Comment by Zearin** [comment]
> One feature AST in, list of pickles out. Gherkin3 has cross platform tests for this

Okay.  

So, I’m not sure if I have this correct.  Is this right?

- Gherkin3 parses `*.feature` file(s), producing JSON AST
- A compiler accepts the AST, producing pickles
- A cucumber test runner accepts the pickles, "glues" the step definitions in, and runs the tests

Does that mean that the compiler is a _separate project_ from Gherkin3 and all the cucumber-* implementations?

**Comment by aslakhellesoy** [comment]
> Gherkin3 parses *.feature file(s), producing JSON AST

It produces an _object_ AST - that can be represented as JSON - for testing purposes. The AST _object_ is passed to the compiler.

> A compiler accepts the AST, producing pickles

That's right, see the 3 implementations we have this far:
* [compiler.rb](https://github.com/cucumber/gherkin3/blob/master/ruby/lib/gherkin3/pickles/compiler.rb)
* [compiler.js](https://github.com/cucumber/gherkin3/blob/master/javascript/lib/gherkin/pickles/compiler.js)
* [Compiler.java](https://github.com/cucumber/gherkin3/blob/master/java/src/main/java/gherkin/pickles/Compiler.java)

> A cucumber test runner accepts the pickles, "glues" the step definitions in, and runs the tests

Pickles are loaded by the [pickle loader](https://github.com/cucumber/microcuke/blob/master/lib/cucumber/pickle_loader.js). The [glue](https://github.com/cucumber/microcuke/blob/master/lib/cucumber/glue.js) (step definitions and hooks) is loaded by a [glue loader](https://github.com/cucumber/microcuke/blob/master/lib/cucumber/glue_loader.js). Then, the glue creates [test cases](https://github.com/cucumber/microcuke/blob/master/lib/cucumber/test_case.js) from the pickles.

Now we have a list of test cases (each of which contains a list of [test steps](https://github.com/cucumber/microcuke/blob/master/lib/cucumber/test_step.js), which represent step definitions or hooks).

The last step is executing everything, which is simply iterating over each test case, asking them to `execute`.

> Does that mean that the compiler is a separate project from Gherkin3 and all the cucumber-* implementations?

It could be, but for convenience it is part of the Gherkin3 codebase.

**Comment by Zearin** [comment]
Okay.  I’ve got a naïve Python compiler.  It was converted largely from the JS implementation, and further informed by the Ruby one.  

How do I test the compiler?  Most the code is “in place”, but I don’t expect it to work yet.  

(I want to develop good testing habits, but I don’t have them yet.  That’s one of the things that drew me to Cucumber and Gherkin in the first place. ☺︎)

**Comment by Zearin** [comment]
**Update:** I’ve got a Python compiler working!  

- I adapted it from (mostly) JS, and a little Java
- Adapted a (pathetic) test from Java
- Added an executable script under `bin/`
- Pull Request opened: cucumber/gherkin3#124

Woo Hoo!
